spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql : true
  main:
    allow-circular-references : true
  application:
    name: USER-SERVICE

  cloud:
    consul:
      host: localhost
      port: 8500
server:
  port: 8081
management:
  security:
    enabled: false


