server:
  port: 8084

spring:
  application:
      name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/**



        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
          filters:
                - AuthenticationFilter

        - id: SERIES-SERVICE
          uri: lb://SERIES-SERVICE
          predicates:
            - Path=/api/series/**
          filters:
            - AuthenticationFilter

        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

    consul:
      host: localhost
      port: 8500

